# Generated by Django 5.2.3 on 2025-12-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('carrot', models.TextField(blank=True)),
                ('stick', models.TextField(blank=True)),
                ('total_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subgoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assigned_days', models.PositiveIntegerField()),
                ('buffer_days', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='goals.goal')),
                ('parent_subgoal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='goals.subgoal')),
            ],
        ),
        migrations.CreateModel(
            name='Timeblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeblocks', to='goals.goal')),
                ('subgoal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeblocks', to='goals.subgoal')),
            ],
        ),
    ]
