# Generated by Django 5.2.3 on 2025-12-12 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='custom_days',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekdays', 'Weekdays (Mon-Fri)'), ('weekends', 'Weekends (Sat-Sun)'), ('alternate', 'Every Other Day'), ('custom', 'Custom Days')], max_length=20),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='task_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeblocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeblocks', to='goals.goal'),
        ),
    ]
